#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iio-sensor-proxy
Version  : 3.0
Release  : 2
URL      : https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.0/iio-sensor-proxy-3.0.tar.gz
Source0  : https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.0/iio-sensor-proxy-3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: iio-sensor-proxy-bin = %{version}-%{release}
Requires: iio-sensor-proxy-config = %{version}-%{release}
Requires: iio-sensor-proxy-data = %{version}-%{release}
Requires: iio-sensor-proxy-services = %{version}-%{release}
BuildRequires : autoconf-archive-dev
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(udev)
BuildRequires : sed

%description
iio-sensor-proxy
================
IIO sensors to D-Bus proxy
See https://developer.gnome.org/iio-sensor-proxy/1.0/ for
developer information.

%package bin
Summary: bin components for the iio-sensor-proxy package.
Group: Binaries
Requires: iio-sensor-proxy-data = %{version}-%{release}
Requires: iio-sensor-proxy-config = %{version}-%{release}
Requires: iio-sensor-proxy-services = %{version}-%{release}

%description bin
bin components for the iio-sensor-proxy package.


%package config
Summary: config components for the iio-sensor-proxy package.
Group: Default

%description config
config components for the iio-sensor-proxy package.


%package data
Summary: data components for the iio-sensor-proxy package.
Group: Data

%description data
data components for the iio-sensor-proxy package.


%package services
Summary: services components for the iio-sensor-proxy package.
Group: Systemd services

%description services
services components for the iio-sensor-proxy package.


%prep
%setup -q -n iio-sensor-proxy-3.0
cd %{_builddir}/iio-sensor-proxy-3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585420242
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1585420242
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iio-sensor-proxy
/usr/bin/monitor-sensor

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/80-iio-sensor-proxy.rules

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system.d/net.hadess.SensorProxy.conf

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/iio-sensor-proxy.service
