#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : iio-sensor-proxy
Version  : 3.5
Release  : 5
URL      : https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.5/iio-sensor-proxy-3.5.tar.gz
Source0  : https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.5/iio-sensor-proxy-3.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: iio-sensor-proxy-bin = %{version}-%{release}
Requires: iio-sensor-proxy-config = %{version}-%{release}
Requires: iio-sensor-proxy-data = %{version}-%{release}
Requires: iio-sensor-proxy-libexec = %{version}-%{release}
Requires: iio-sensor-proxy-license = %{version}-%{release}
Requires: iio-sensor-proxy-services = %{version}-%{release}
BuildRequires : autoconf-archive-dev
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : libgudev-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(udev)
BuildRequires : polkit-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
iio-sensor-proxy
================
IIO sensors to D-Bus proxy
See https://developer.gnome.org/iio-sensor-proxy/1.0/ for
developer information.

%package bin
Summary: bin components for the iio-sensor-proxy package.
Group: Binaries
Requires: iio-sensor-proxy-data = %{version}-%{release}
Requires: iio-sensor-proxy-libexec = %{version}-%{release}
Requires: iio-sensor-proxy-config = %{version}-%{release}
Requires: iio-sensor-proxy-license = %{version}-%{release}
Requires: iio-sensor-proxy-services = %{version}-%{release}

%description bin
bin components for the iio-sensor-proxy package.


%package config
Summary: config components for the iio-sensor-proxy package.
Group: Default

%description config
config components for the iio-sensor-proxy package.


%package data
Summary: data components for the iio-sensor-proxy package.
Group: Data

%description data
data components for the iio-sensor-proxy package.


%package libexec
Summary: libexec components for the iio-sensor-proxy package.
Group: Default
Requires: iio-sensor-proxy-config = %{version}-%{release}
Requires: iio-sensor-proxy-license = %{version}-%{release}

%description libexec
libexec components for the iio-sensor-proxy package.


%package license
Summary: license components for the iio-sensor-proxy package.
Group: Default

%description license
license components for the iio-sensor-proxy package.


%package services
Summary: services components for the iio-sensor-proxy package.
Group: Systemd services
Requires: systemd

%description services
services components for the iio-sensor-proxy package.


%prep
%setup -q -n iio-sensor-proxy-3.5
cd %{_builddir}/iio-sensor-proxy-3.5
pushd ..
cp -a iio-sensor-proxy-3.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1690391969
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/iio-sensor-proxy
cp %{_builddir}/iio-sensor-proxy-%{version}/COPYING %{buildroot}/usr/share/package-licenses/iio-sensor-proxy/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/monitor-sensor
/usr/bin/monitor-sensor

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/80-iio-sensor-proxy.rules

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system.d/net.hadess.SensorProxy.conf
/usr/share/polkit-1/actions/net.hadess.SensorProxy.policy

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/iio-sensor-proxy
/usr/libexec/iio-sensor-proxy

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iio-sensor-proxy/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/iio-sensor-proxy.service
